### ISSUE TITLE
Question: Which external systems are set?

### ISSUE THREAD

**Issue by mwmahlberg** [gengstrand/clojure-news-feed#8]
Upon reading your [question on SO](https://stackoverflow.com/questions/57762297/why-does-using-more-structs-degrade-performance-in-go), I decided to reimplement the go server to a more proper version of it. I will replace Redis with [groupcache](https://github.com/golang/groupcache) most likely, since it makes better use of the RAM of the nodes running the server. But I wonder wether MySQL is required, maybe because of (legacy )integration. Note however that this in itself is arguable, since integration via database is questionable at best.

If it is not required to use MySQL, please let me know. The same goes for Cassandra.

**Comment by gengstrand** [comment]
MySql is used to store participant and friend relationship data in a persistent manner. Cassandra is used to store news feed item inbound and outbound data in a persistent manner.

This repo is used for research purposes. For each experiment, you get to alter only one thing. Otherwise, the experiment is invalid because you won't know which thing you altered caused the difference in results. For the purposes of this repo, that would be the runtime environment (i.e. programming language and libraries). This is why each implementation uses the same datastores.

There is more that goes into the choice of programming language than comparing compiler focused benchmarks. An important part to evaluating microservice appropriate runtimes is the ecosystem. Has stable and efficient are the client libraries for the most popular datastores? That is why each news feed implementation is polyglot persistent.

**Comment by mwmahlberg** [comment]
I am not sure I agree. With regards to the ecosystem, I could argue that [bleve](https://github.com/blevesearch/bleve) could easily substitute for elasticsearch. Or, the other way around, instead of testing the performance of languages themselves, the driver implementations are evaluated if the project is not strictly self-contained with the exception of the standard library.

However, I can see a reason for the approach. I presume we are talking of single instance API servers?

**Comment by gengstrand** [comment]
The load test is set up with but a single replica but the system should follow the 12 factors to some significant degree.

**Comment by mwmahlberg** [comment]
See #11 
Please let me know wether to accept the PR.

Furthermore, I am pretty sure that replacing redis with a local cache on each of the application servers will drastically speed up the application. I played with a simple map, and the results were... In orders of magnitude. There are even cache libraries which replicate, like @ [vegamcache](https://github.com/balajijinnah/vegamcache), which sounds suitable for your use case.

**Comment by gengstrand** [comment]
Hmmm, you have a different approach to PRs than what I have seen before. Normally, you open a PR with changes to the files. Instead, you created a new folder and put your implementation there. With your approach, it is hard to see what has changed. The only real material change that I see here is caching the prepared statements. Is that right?

I am guessing that you prefer docker compose over Kubernetes. Is that right? Have you run your service in the load test that I provided? What were the results?

**Comment by gengstrand** [comment]
Regarding the replacement of an external cache with a local cache, that is a classic example of choosing performance over scalability. Multiple pods, where each pod has a local cache, will result in dirty reads (i.e. the locally cached version will not be the latest) which will force you to always run it on only one pod.

**Comment by mwmahlberg** [comment]
I am not caching them. The code is well documented. I admittedly started to get carried away, and when I noticed, I thought it made more sense to have a side by side comparison of feed9 and feed 10. Regarding the files, you might want to read them and comment where you are unclear.

vegamcache *replicates* itself between the nodes. Just like group cache does. Think of it like hazelcast or ehcache (which both have the option of replicating themselves between the nodes).

**Comment by gengstrand** [comment]
Replicated local caches do not solve the dirty read problem. See this [comment](https://www.infoq.com/articles/obscuring-complexity/#anch169456) for more details.

**Comment by mwmahlberg** [comment]
Ok. I give up. Sorry for bothering.

**Comment by gengstrand** [comment]
Too bad. Here is something else I noticed. Prepared statements are [scoped to the connection](https://www.vividcortex.com/blog/2014/07/10/4-things-to-know-about-mysql-prepared-statements/) in which they were prepared. When you prepare statements and store them in single package scoped variables that means every time you execute that statement in that single variable, you are using the same database connection. That means you would not really be using a connection pool.
